# If you accidentally unbind &studio_unlock, uncomment to disable locking and reflash to get yourself back in.
# Permanently disabling locking is not advised as that will allow any program to change your keymap at any time.
#CONFIG_ZMK_STUDIO_UNLOCK=n

# Uncomment to disable underglow.
#CONFIG_ZMK_RGB_UNDERGLOW=n

# Increase wireless transmission power at the cost of a little battery life.
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Some operating systems (currently macOS, Android) have problems with full support for consumer keycodes.
# If yours does not, comment this out in order for keycodes like C_AL_CALC to work.
CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_BASIC=y

# Disabling PHY 2Mbps
CONFIG_BT_CTLR_PHY_2M=n

# keyboard name
CONFIG_ZMK_KEYBOARD_NAME="ALU40v2"
CONFIG_BT_DEVICE_NAME="ALU40v2"

CONFIG_ZMK_BLE_THREAD_STACK_SIZE=2048
CONFIG_INPUT_THREAD_STACK_SIZE=1024


CONFIG_SPI=y
CONFIG_LED_STRIP=y
CONFIG_WS2812_STRIP=y

# Enable WS2812 widget
CONFIG_RGBLED_WIDGET=y
CONFIG_RGBLED_WIDGET_WS2812=y

# 2 LEDs with spatial mapping
CONFIG_RGBLED_WIDGET_LED_COUNT=2
CONFIG_RGBLED_WIDGET_SPATIAL_MAPPING=y
CONFIG_RGBLED_WIDGET_LED_SHARING=y

# LED assignments
CONFIG_RGBLED_WIDGET_BATTERY_LED_INDEX=0
CONFIG_RGBLED_WIDGET_CONN_LED_INDEX=1
CONFIG_RGBLED_WIDGET_LAYER_SHARE_BATTERY=y
CONFIG_RGBLED_WIDGET_LAYER_SHARE_CONN=y

# Appearance
CONFIG_RGBLED_WIDGET_BRIGHTNESS=96
CONFIG_RGBLED_WIDGET_SHARE_TIMEOUT_MS=500